### ISSUE TITLE
Exceeds maximum 2712 for index "cities_light_city_search_names"

### ISSUE THREAD

**Issue by mikaelosterberg** [yourlabs/django-cities-light#152] opened 2017-07-07 08:43 UTC
Settings
`CITIES_LIGHT_TRANSLATION_LANGUAGES = [
    'abbr', 'se', 'en',  'no', 'fi',  'da',
]
CITIES_LIGHT_INCLUDE_CITY_TYPES = [
    'PPL', 'PPLA', 'PPLA2', 'PPLA3', 'PPLA4', 'PPLC', 'PPLCH', 'PPLF', 'PPLG', 'PPLH', 'PPLL', 'PPLQ', 'PPLR', 'PPLS',
    'PPLW', 'PPLX',
]
CITIES_LIGHT_INDEX_SEARCH_NAMES = True
`
Error
`RAM used: 328278016 kB ETA: 0:00:10 Done:  25%|####################                                                            |Traceback (most recent call last):
  File "/Users/mikaelosterberg/Development/mikaelosterberg/Envs/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: index row size 2824 exceeds maximum 2712 for index "cities_light_city_search_names_fb77fed2"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.`

**Comment by mikaelosterberg** [comment] 2017-07-07 10:55
Works when
`CITIES_LIGHT_INDEX_SEARCH_NAMES = False`

Django==1.11.2
django-cities-light==3.3.0

**Comment by jpic** [comment] 2017-07-11 10:27
Sounds reasonable, @max-arnold what's your take on this ?

**Comment by max-arnold** [comment] 2017-07-11 11:12
`CITIES_LIGHT_INDEX_SEARCH_NAMES` is True by default, are you suggesting to switch it off?

**Comment by max-arnold** [comment] 2017-07-11 11:19
Related Django bug: https://code.djangoproject.com/ticket/14904
Also there is postgres-specific full text search functions: https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/search/

**Comment by max-arnold** [comment] 2017-07-11 11:20
Duplicate of #115

**Closed** 2018-02-24 22:26 UTC
