### ISSUE TITLE
Reverse accessor clashes

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [yourlabs/django-cities-light#116] opened 2016-04-22 13:15 UTC
Having imported everything as I oughta, I get the following:

```
ERRORS:
cities_light.City.country: (fields.E304) Reverse accessor for 'City.country' clashes with reverse accessor for 'City.country'.
    HINT: Add or change a related_name argument to the definition for 'City.country' or 'City.country'.
cities_light.City.region: (fields.E304) Reverse accessor for 'City.region' clashes with reverse accessor for 'City.region'.
    HINT: Add or change a related_name argument to the definition for 'City.region' or 'City.region'.
cities_light.Region.country: (fields.E304) Reverse accessor for 'Region.country' clashes with reverse accessor for 'Region.country'.
    HINT: Add or change a related_name argument to the definition for 'Region.country' or 'Region.country'.
pandion_api.City.country: (fields.E304) Reverse accessor for 'City.country' clashes with reverse accessor for 'City.country'.
    HINT: Add or change a related_name argument to the definition for 'City.country' or 'City.country'.
pandion_api.City.region: (fields.E304) Reverse accessor for 'City.region' clashes with reverse accessor for 'City.region'.
    HINT: Add or change a related_name argument to the definition for 'City.region' or 'City.region'.
pandion_api.Region.country: (fields.E304) Reverse accessor for 'Region.country' clashes with reverse accessor for 'Region.country'.
    HINT: Add or change a related_name argument to the definition for 'Region.country' or 'Region.country'.
```

Am I doing something wrong here?

**Comment by helio-correia** [comment] 2016-11-24 16:24
I'm having the same problem, do you find a solution?

**Comment by max-arnold** [comment] 2016-11-24 16:38
Have no idea how to reproduce this without specific details like python/django/cities-light versions, and any tweaks/settings you've made.

**Comment by helio-correia** [comment] 2016-11-24 16:52
No problem, I am running python3.5.0 with django 1.10.3 and cities-light 3.3.0
i have a app with this
```
from django.db import models
from django.utils.translation import ugettext_lazy as _

from cities_light.models import City

from accounts.models import ClubUser


class Address(models.Model):
    postal_code = models.CharField(_('postal code'), max_length=20)
    street = models.TextField(_('street'))
    additional_information = models.TextField(_('additional information'), blank=True)
    city = models.OneToOneField(City, verbose_name=_('city'))

    class Meta:
        abstract = True


class AddressUser(Address):
    user = models.ForeignKey(ClubUser, on_delete=models.CASCADE, verbose_name=_('user'), related_name='addresses')
    phone = models.CharField(_('phone'), max_length=20)
    description = models.CharField(_('description'), max_length=50, blank=True,
                                   help_text=_('description of the address, can be home, office or whatever you want'))

    def __str__(self):
        return self.description or self.street
```
the project is running fine and when i put in my settings this ```CITIES_LIGHT_APP_NAME = _('places')``` i receive the error ```ImportError: cannot import name 'City'```.

Then I try the documentation on this link http://django-cities-light.readthedocs.io/en/stable-3.x.x/full.html#models and when i try to migrate it gives the error that chrisvoncsefalvay mentioned.

After that my first try wast to migrate cities-light zero and migrate again but I receive the same error.

I'm doing the right way on my model Address with this code `city = models.OneToOneField(City, verbose_name=_('city'))`?

Thanks for the reply :)

**Comment by jpic** [comment] 2016-11-25 00:17
Instead of importing City at the top, could you try that ?

    city = models.OneToOneField('cities_light.City', verbose_name=_('city'))
​
Don't set CITIES_LIGHT_APP_NAME unless you want to override the models: in
your example it's just a relation to the default City models that you need.

**Comment by helio-correia** [comment] 2016-11-29 11:30
The thing i was trying to do as set CITIES_LIGHT_APP_NAME, i didn't know that i must need to override the models to do that

**Comment by max-arnold** [comment] 2017-07-26 11:57
It looks like the issue was related to misconfiguration, closing.

**Closed by max-arnold** 2017-07-26 11:57 UTC
