### ISSUE TITLE
Running makemigrations creates new migration file 0004_auto_20150730_2004.py

### ISSUE THREAD

**Issue by saeedsq** [yourlabs/django-cities-light#96] opened 2015-07-30 16:15 UTC
It happens with django-cities-light==3.1.2, django-autoslug==1.8.0, django==1.8.3

Migrations for 'cities_light':
  0004_auto_20150730_2004.py:
    - Alter field slug on city
    - Alter field slug on country
    - Alter field slug on region

```python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0003_auto_20141120_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=autoslug.fields.AutoSlugField(populate_from=b'name_ascii', editable=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=autoslug.fields.AutoSlugField(populate_from=b'name_ascii', editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=autoslug.fields.AutoSlugField(populate_from=b'name_ascii', editable=False),
        ),
    ]

```

This issue does not occurs with django_autoslug==1.7.2

**Comment by jpic** [comment] 2015-08-03 11:57
Maybe we could add it to django-cities-light then, what do you think ?

Note that there has been a related discussion recently: https://groups.google.com/forum/#!topic/django-developers/WgFacUFvgfs

**Comment by saeedsq** [comment] 2015-08-03 16:23
Two issues:
1) Django create migration files repeatedly if you change model field dynamically.
2) Django autochecks every single attribute of model fields for migration changes. (which I do not see eye to eye with django developers in this case)

I go with adding requirement version django_autoslug==1.7.2, Since Django developers are planing to refactor internal migration process. And Since other developers would install the latest version not knowing which version matches the best.


Personally I have added the exact version of django_autoslug to my project requirements.

**Comment by jpic** [comment] 2015-08-10 10:05
Should we pin django_autoslug then ?

**Comment by mauricioabreu** [comment] 2015-09-18 20:22
This error happens to me even downgrading django autoslug.

**Comment by jpic** [comment] 2015-12-13 15:31
Could you guys please try PR #101 see if it fixes it ?

**Comment by jpic** [comment] 2015-12-29 15:50
Anyone ? ;0

**Comment by mauricioabreu** [comment] 2015-12-29 16:59
Hey @jpic 
My case solved downgrading autoslug. Not sure if your PR would solve the problem I had. Not sure how to help you in here.

**Comment by jpic** [comment] 2015-12-29 18:30
Your fix is palliative, it would be better to have a curative fix here.

Could you try with the current stable autoslug version and the PR please ?

**Comment by mauricioabreu** [comment] 2015-12-29 18:38
The environment is the one I have at work, not here (I am on vacation :P)
But my stack is based on Python 2.6, Django 1.6 and MySQL Percona. django-cities-light is not intended to work with Python 2.6 so I was wrong in many ways.

If it is working and the build is passing it is ok. I think that PR will solve @saeedsq issue and for anyone who is facing it.

**Comment by jpic** [comment] 2015-12-29 19:41
Thanks, I just found a regression test ^^

https://github.com/yourlabs/django-cities-light/commit/78e92065bdaf5132da1d26f88c96aded38d4158b#diff-1b531c5e405e0bc95890d52cf2f2f5b5R8

Closing in favor of PR.

**Closed by jpic** 2015-12-29 19:41 UTC

**Comment by jpic** [comment] 2016-01-10 13:08
A fix has been released in 3.2.0.

**Comment by pdonaire1** [comment] 2016-04-19 15:37
The solution that y recommend is:
1) download the folder cities_light to a django apps.
2) replace the file name "0004_auto_20150730_2004.py" by the name that has the migrations file in the number 0004_auto.....
And that's it, Django-cities do migratinos but if you are working with a team, and they are working with diferents machines, you have to make this soluciones, because when you do a migrations, these migrations are created  in the folder cities_light into the virtual machine.

**Comment by jpic** [comment] 2016-04-19 16:19
This is a palliative solution and not recommended.
